meta_data:
  script_path: run_scripts/bmg_exp_script.py
  exp_name: test_bmg_ant
  description: Train an agent using Bootstrapped Meta Gradient
  num_workers: 2
  using_gpus: true
# -----------------------------------------------------------------------------
variables:
  seed: [0]

# -----------------------------------------------------------------------------
constants:
  net_size: 256
  meta_net_size: 128
  num_hidden_layers: 2
  inference_reward_num: 10
  inner_loop_steps: 8
  bootstrap_loop_steps: 8
  matching_loss: "mse"
  matching_mean_coef: 1.0
  matching_std_coef: 1.0
  meta_start_epoch: 20

  rl_alg_params:
    num_epochs: 200
    num_steps_per_epoch: 10000
    num_steps_between_train_calls: 100
    num_train_steps_per_train_call: 100
    num_steps_per_eval: 10000
    max_path_length: 1000
    min_steps_before_training: 1000

    eval_deterministic: true

    batch_size: 512
    replay_buffer_size: 1000000
    no_terminal: false
    wrap_absorbing: false

    save_best: true
    freq_saving: 10
    save_replay_buffer: false
    # save_environment: true
    # save_algorithm: true

  sac_params:
    alpha: 0.2
    reward_scale: 1.0
    discount: 0.99
    soft_target_tau: 0.005
    policy_lr: 0.0003
    qf_lr: 0.0003
    vf_lr: 0.0003
    policy_mean_reg_weight: 0.001
    policy_std_reg_weight: 0.001
    target_entropy: -4

  env_specs:
    env_name: 'ant'
    env_kwargs: {}
    env_num: 2
